const Map<String, List<String>> kRegionsByCountry = {
  'O‘zbekiston': [
    'Toshkent viloyati',
    'Andijon viloyati',
    'Farg\'ona viloyati',
    'Namangan viloyati',
    'Samarqand viloyati',
    'Buxoro viloyati',
    'Navoiy viloyati',
    'Qashqadaryo viloyati',
    'Surxondaryo viloyati',
    'Jizzax viloyati',
    'Sirdaryo viloyati',
    'Xorazm viloyati',
    'Qoraqalpog\'iston Respublikasi',
  ],

  'Qozog‘iston': [
    'Abay viloyati',
    'Akmola viloyati',
    'Aktobe viloyati',
    'Almati viloyati',
    'Atyrau viloyati',
    'Sharqiy Qozog\'iston viloyati',
    'Jambyl viloyati',
    'Jetisu viloyati',
    'G\'arbiy Qozog\'iston viloyati',
    'Qarag\'anda viloyati',
    'Qostanay viloyati',
    'Qizilo\'rda viloyati',
    'Mang\'istau viloyati',
    'Pavlodar viloyati',
    'Shimoliy Qozog\'iston viloyati',
    'Turkiston viloyati',
    'Ulytau viloyati',
  ],

  'Qirg‘iziston': [
    'Botken viloyati',
    'Chuy viloyati',
    'Jalolobod viloyati',
    'Issiqko‘l viloyati',
    'Narin viloyati',
    'O\'sh viloyati',
    'Talas viloyati',
  ],

  'Tojikiston': [
    'Sug\'d viloyati',
    'Xatlon viloyati',
    'GBAO',
  ],

  'Turkmaniston': [
    'Ahal viloyati',
    'Balkan viloyati',
    'Dashoguz viloyati',
    'Lebap viloyati',
    'Mary viloyati',
  ],
};