// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn_1-ffF7Qon2n4QKXpdNv16OCuZJc2ys',
    appId: '1:225052370906:web:a45f608a746ecc97fa42e3',
    messagingSenderId: '225052370906',
    projectId: 'nature-go-c188e',
    authDomain: 'nature-go-c188e.firebaseapp.com',
    databaseURL: 'https://nature-go-c188e-default-rtdb.firebaseio.com',
    storageBucket: 'nature-go-c188e.firebasestorage.app',
    measurementId: 'G-MCT40MLNQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyjN7sk4mfDlgLC6DvNT3V2WGp8mGN_aU',
    appId: '1:225052370906:android:0371f1994f44acb4fa42e3',
    messagingSenderId: '225052370906',
    projectId: 'nature-go-c188e',
    databaseURL: 'https://nature-go-c188e-default-rtdb.firebaseio.com',
    storageBucket: 'nature-go-c188e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByJ742EWFX9xIv-L2K1Ja3_iBuhLIJ2d0',
    appId: '1:225052370906:ios:8180a032abdba80ffa42e3',
    messagingSenderId: '225052370906',
    projectId: 'nature-go-c188e',
    storageBucket: 'nature-go-c188e.firebasestorage.app',
    iosBundleId: 'com.example.natureGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByJ742EWFX9xIv-L2K1Ja3_iBuhLIJ2d0',
    appId: '1:225052370906:ios:8180a032abdba80ffa42e3',
    messagingSenderId: '225052370906',
    projectId: 'nature-go-c188e',
    storageBucket: 'nature-go-c188e.firebasestorage.app',
    iosBundleId: 'com.example.natureGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn_1-ffF7Qon2n4QKXpdNv16OCuZJc2ys',
    appId: '1:225052370906:web:0548524d96b3e390fa42e3',
    messagingSenderId: '225052370906',
    projectId: 'nature-go-c188e',
    authDomain: 'nature-go-c188e.firebaseapp.com',
    storageBucket: 'nature-go-c188e.firebasestorage.app',
    measurementId: 'G-22XM7SMV5F',
  );
}